name: dashcast
description: A podcast player written in Flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_sound: ^1.4.5
  webfeed: ^0.4.2
  cupertino_icons: ^0.1.2	  
  http: ^0.12.0+2
  provider: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/surf_shimmy.mp3